AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  PorperLambdaLayerMySQL2:
      Type: AWS::Serverless::LayerVersion
      Properties:
          Description: Porper Core as a Layer
          ContentUri: ./src
          CompatibleRuntimes:
            - python3.6
            - python3.7
Outputs:
  PorperLambdaLayerArn:
    Description: "Porper Lambda Layer ARN"
    Value: !Ref PorperLambdaLayer
    Export:
      Name: !Sub "${AWS::StackName}-PorperLambdaLayerArn"
