AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  PorperLambdaMySQL2Layer:
      Type: AWS::Serverless::LayerVersion
      Properties:
          Description: Porper Core as a Layer
          ContentUri: ./src
          CompatibleRuntimes:
            - python3.6
            - python3.7
Outputs:
  PorperLambdaMySQL2LayerArn:
    Description: "Porper Lambda MySQL2 Layer ARN"
    Value: !Ref PorperLambdaMySQL2Layer
    Export:
      Name: !Sub "${AWS::StackName}-PorperLambdaMySQL2LayerArn"
